User can specify columns to show in the list. Supported columns: language, type, author, tags
dotnet/templating pull request #2605
Opened 2020-10-26 15:00 UTC by vlada-shubina

Implemented: 
- support for INewCommandInput to parse columns to show in the table
- support for HelpFormatter<T> to filter columns to show using information from INewCommandInput

Added:
- ability to show type and template author for list. By default these columns are not shown but user can opt to show it using --columns option.

fixes https://github.com/dotnet/templating/issues/2470
required for https://github.com/dotnet/templating/issues/2571

2020-10-26 17:19 UTC, donJoseLuis approved these changes
minor comments

2020-10-26 17:19 UTC, donJoseLuis commented on src/Microsoft.TemplateEngine.Cli/CommandParsing/NewCommandInputCli.cs
> +{
minor: the formatting of this starting curly bracket is a bit off

2020-10-26 17:19 UTC, donJoseLuis commented on src/Microsoft.TemplateEngine.Cli/CommandParsing/NewCommandInputCli.cs
> +                List<string> invalidColumns = new List<string>();
minor: consider instantiating these types with a specified capacity.

[List<T> .ctor ](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.-ctor?view=netcore-3.1#System_Collections_Generic_List_1__ctor_System_Int32_)

2020-10-27 19:07 UTC, grinrag requested changes
minor: some trailing spaces were added

2020-10-27 19:07 UTC, grinrag commented on src/Microsoft.TemplateEngine.Cli/CommandParsing/CommandParserSupport.cs
> +            }
trailing spaces

2020-10-29 10:23 UTC, grinrag approved these changes
LGTM

2020-10-29 10:33 UTC, merged