Integrate into localization pipeline
dotnet/templating pull request #2888
Opened 2021-02-25 11:15 UTC by bozturkMSFT

### Problem
Fixes https://github.com/dotnet/templating/issues/2137.
TE is still part of the old localization pipeline (with .lcl files), which is abandoned across dotnet projects. We need to start using Xliff tools (included in and supported by arcade).

### Solution
Xliff tool is enabled in arcade settings.
Microsoft.TemplateEngine.CLI is marked as shipping to allow translations. It was previously marked non-shipping [here](https://github.com/dotnet/templating/pull/2569), but I don't think the motivation for that PR is still valid (System.CommandLine is still being shipped by bot dotnet-cli and templating engine, despite being marked as non-shipping). Details to be discussed internally in weekly sync meeting.

### Checks:
- [ ] Added unit tests (**No. Reason: non-testable infra work**)
- [ ] Added `#nullable enable` to all the modified files [?](https://github.com/dotnet/templating/wiki/Contributing#coding-style)(**Not applicable. No code files were updated.**)

2021-02-25 12:37 UTC, bozturkMSFT commented
I removed the old `.lcl` files since they are no longer used. We should pass them to loc team to help them translate the `.xlf`s.

2021-03-02 14:19 UTC, vlada-shubina requested changes

2021-03-03 17:11 UTC, bozturkMSFT commented on src/Microsoft.TemplateEngine.Cli/Microsoft.TemplateEngine.Cli.csproj
> -		<IsShipping>false</IsShipping>
Addressed the issue by settings `IsShippingPackage` to `false`. The project is still "shipping", but it is not "shipping a package". Some arcade specific details are [here](https://github.com/dotnet/arcade/blob/master/Documentation/ArcadeSdk.md#isshipping-isshippingassembly-isshippingpackage-isshippingvsix-bool).

2021-03-03 17:19 UTC, vlada-shubina approved these changes

2021-03-03 17:26 UTC, DavidKarlas approved these changes
I'm disappointed that `tr` is not translated :P

2021-03-03 17:33 UTC, merged