Template Discovery: incremental updates
dotnet/templating pull request #3716
Opened 2021-08-20 17:52 UTC by vlada-shubina

### Problem
https://github.com/dotnet/templating/issues/3233

### Solution
Implemented incremental updates for search cache

TODO:
- check if number of packages discovered is not less than previous time
  - if the package is missing, check if it is unlisted

- add more tests

### Checks:
- [ ] Added unit tests - TBD
- [x] Added `#nullable enable` to all the modified files [?](https://github.com/dotnet/templating/wiki/Contributing#coding-style)

2021-08-30 14:56 UTC, vlada-shubina commented
Example of summary shown in the end of the run:
```
Run summary:
Template packages:
   new: 55
      Feliz.Template::3.12.0
      Take.Blip.Client.ConsoleTemplate::0.1.30
      Paulovich.Manga::0.0.7
      Progress.AspNetCore.SpaTemplates::1.0.1
      MicroServiceWebApiTemplate::0.1.3
      DotNetCore2WebApiTemplate::1.0.0
      OASP4Net.Test.Template::1.0.0
      NetNinja.Api.Template::1.0.0
      Wiz.Dotnet.Template.Function.DataDriven::1.1.27974
      NetNinja.Graphql.Api.Template::1.0.0
      Wiz.Dotnet.Template.API.DataDriven::1.1.26703
      WebAPIMongodbTemplate::1.0.2
      AsyncConsole::1.1.1
      Blog.Corezy.Webapi.Template::1.0.0
      kirov-webapi-test::1.1.1
      Frank.Core.Webapi.Template::1.1.0
      Malpe.Leaf.Module::2.8.0
      superuser-chi.utility.templates::1.0.1
      KZM.Utility.Templates::1.0.0
      ExitoDDD.Template.CSharp::1.0.0
      Empowered.NetCoreTemplates::1.3.0
      OA.RSI.Architecture.WebApi.Template::1.0.0
      Xiaobao.Ddd.Template.Test.ZW::1.0.3
      ABC.Utility.Templates::1.0.0
      Mumby.Templates.nuspec::1.0.0
      Xiaobao.Ddd.Template.A::1.0.0
      Maple.Branch.Module.Template::1.0.0
      Custom.Template.NetCore.ZWT::1.0.1
      Dummy.Utility.Templates::1.0.0
      Xiaobao.Ddd.Template.TTTT::1.0.0
      WebJob.Utility.Templates::1.0.0
      Genocs.CleanArchitecture::0.1.0
      Exito.Project.Templates::1.0.0
      YWDNetCoreWebApi::1.0.0
      Xiaobao.Ddd.Template.TT::1.0.0
      Blog.Template::1.0.0
      WebJobLogic.Utility.Templates::1.0.0
      Xiaobao.Ddd.Template.TTT::1.0.0
      EDAQuickstart.Templates2::1.0.0
      CleanApiTemplate.WebApi.CSharp.Templates::1.0.0
      WebApi.BDMS.Core.Template.HGD::1.0.0
      Lean-NET5::1.0.2
      1821JiangHao.Souvenir.Temple::1.0.0
      ZouYaoLu.Framework.Template::1.0.0
      OSharpNS.Template.WebApi::5.0.5.419
      ShenNius.WebApi.Template::1.2.0
      VijayAnand.BlazorTemplates::1.0.0
      JithinK.Template.CATool.nuspec::1.0.1
      Oleksii.Template.HerokuNet5Web.nuspec::1.0.0
      ConsoleCoreTemple.Template::1.0.0
      Template.Api.Multi.Tenancy::1.0.0
      VBorisof.NetCoreApiTemplate::1.0.0
      partners_igia_microservice_template::1.0.0.4
      FoxPro.RageMPResourceTemplate.CSharp::1.0.0
      bcxwebapi::1.0.0
   updated: 1
      FriscoVInc.DotNet.Templates.CleanBlazor, 1.1.2 --> 1.1.3
   removed: 0
   not changed: 1085
Non template packages:
   new: 31
   updated: 97
   removed: 1
   not changed: 2445
   unavailable: 0
```

2021-08-30 17:06 UTC, bekir-ozturk requested changes

2021-08-31 13:01 UTC, vlada-shubina commented on src/Microsoft.TemplateSearch.TemplateDiscovery/AdditionalData/CliHostDataProducer.cs
> +            }
I would tend not to do it. In theory, we can add more fields to host data. For search cache we only care for 2 of them

2021-08-31 13:13 UTC, vlada-shubina commented on src/Microsoft.TemplateSearch.TemplateDiscovery/PackChecking/PackSourceChecker.cs
> +                        await provider.DeleteDownloadedPacksAsync().ConfigureAwait(false);
Implementations of `DeleteDownloadedPacksAsync` should not throw now, I can add try/catch just in case something wrong happens.

2021-08-31 14:26 UTC, bekir-ozturk approved these changes

2021-09-01 07:20 UTC, merged