[feature/constraints] abstractions and main APIs for constraints implementation
dotnet/templating pull request #4606
Opened 2022-04-18 15:23 UTC by vlada-shubina

### Problem
#3107 

### Solution
abstractions and main API definition.
draft: pending unit tests for `Edge`.

### Checks:
- [ ] Added unit tests
- [x] Added `#nullable enable` to all the modified files [?](https://github.com/dotnet/templating/wiki/Contributing#coding-style)

2022-04-26 15:06 UTC, JanKrivanek requested changes
Overall looks good.
I'd only advice revisiting the case with not honored `CancellationToken`

2022-04-26 15:06 UTC, JanKrivanek commented on src/Microsoft.TemplateEngine.Utils/WellKnownSearchFilters.cs
> +                        return null;
Cannot this fall under the Match case? It might simplify the logic and remove the need for `null`s

2022-04-26 17:46 UTC, JanKrivanek approved these changes

2022-04-27 03:13 UTC, DavidKarlas approved these changes

2022-04-28 06:49 UTC, merged