Use package version properties for dependabot project during source build
dotnet/templating pull request #4941
Opened 2022-07-11 22:48 UTC by lbussell

### Context
See https://github.com/dotnet/source-build/issues/2933 and https://github.com/dotnet/msbuild/pull/7798

### Changes Made

- Set PackageReferences to versions specified by their respective `*Version` properties (like `SystemCodeDomVersion` for example). We define and import properties for packages that are available during source-build and use this to overwrite the dependabot-managed versions of these packages.
- During a non-source-build build, these dependencies should all be set to their dependabot-managed versions, since none of these dependencies have versions properties defined in `eng/Versions.props`.

If dependabot has trouble reading and updating these dependencies after this update, then of course we can revert this change and re-evaluate our approach.

2022-07-12 12:15 UTC, vlada-shubina requested changes
I would also put all source-build related references under `IsSourceBuild == true` condition to be on safe side.

2022-07-12 12:15 UTC, vlada-shubina commented on eng/dependabot/Packages.props
> +    <PackageReference Update="FakeItEasy" Condition="'$(FakeItEasy)' != ''" Version="$(BenchmarkDotNetVersion)" />
this doesn't look correct

2022-07-12 12:15 UTC, vlada-shubina commented on eng/dependabot/Packages.props
> +    <PackageReference Update="System.Runtime.Loader" Condition="'$(SystemRuntimeLoader)' != ''" Version="$(SystemRuntimeLoader)" />
```suggestion
    <PackageReference Update="System.Runtime.Loader" Condition="'$(SystemRuntimeLoaderVersion)' != ''" Version="$(SystemRuntimeLoaderVersion)" />
```

Should it be similar in all cases below?

2022-07-12 15:42 UTC, vlada-shubina commented on eng/dependabot/Packages.props
> +    <PackageReference Update="System.Runtime.Loader" Condition="'$(SystemRuntimeLoader)' != ''" Version="$(SystemRuntimeLoaderVersion)" />
```suggestion
    <PackageReference Update="System.Runtime.Loader" Condition="'$(SystemRuntimeLoaderVersion)' != ''" Version="$(SystemRuntimeLoaderVersion)" />
```

more typos here and below

2022-07-13 08:15 UTC, vlada-shubina approved these changes
LGTM

2022-07-13 18:26 UTC, lbussell commented
@vlada-shubina Please merge when appropriate.

2022-07-14 07:33 UTC, merged