Update VM images for Windows and Linux
dotnet/templating pull request #5311
Opened 2022-09-23 09:33 UTC by GangWang01

### Problem

- #5002
- ubuntu-18.04 is deprecated.

### Solution

### Checks:
- [ ] Added unit tests
- [ ] Added `#nullable enable` to all the modified files [?](https://github.com/dotnet/templating/wiki/Contributing#coding-style)

2022-09-23 14:00 UTC, JanKrivanek commented
Looks good.
We should make this change on 7.0.1xx as well

2022-09-26 08:04 UTC, vlada-shubina requested changes

2022-09-26 08:04 UTC, vlada-shubina commented on azure-pipelines.yml
>                demands: ImageOverride -equals Build.Ubuntu.1804.Amd64
this also needs to be updated, i hope just changing the version works.

2022-09-26 09:24 UTC, vlada-shubina commented
> Looks good. We should make this change on 7.0.1xx as well

We should make it on all active branches (7.0.1xx, 7.0.1xx-rc2, 6.0.1xx, 6.0.3xx, 6.0.4xx, 3.1).

2022-09-26 10:32 UTC, vlada-shubina approved these changes

2022-09-26 11:19 UTC, merged