emplates for template authoring: first draft
dotnet/templating pull request #5739
Opened 2022-12-07 14:56 UTC by vlada-shubina

### Problem
fixes https://github.com/dotnet/templating/issues/2722

### Solution
Adds the template package with templates for template authoring.

TODO:
- post actions asking to fill TODOs
- validation of the fields

### Checks:
- [ ] Added unit tests - waits for `Verify` tests to be available
- [ ] Added `#nullable enable` to all the modified files [?](https://github.com/dotnet/templating/wiki/Contributing#coding-style) - N/A

2022-12-08 12:41 UTC, JanKrivanek commented
Do we want to add template for host config file?

2022-12-08 13:02 UTC, JanKrivanek requested changes
Great addition!! To mee it almost feel this should be part of sdk :-)

I'd just adjust the json template so that it's valid as is

2022-12-08 15:22 UTC, vlada-shubina commented on template_feed/Microsoft.TemplateEngine.Authoring.Templates/content/TemplateJson/template.json
> +  "_comment": "See https://github.com/dotnet/templating/wiki/Reference-for-template.json for complete configuration description. Complete TODOs below and remove the _comment properties.It is recommen
Good catch, however apparently it's only allowed on top level :(

2022-12-08 15:23 UTC, vlada-shubina commented on template_feed/Microsoft.TemplateEngine.Authoring.Templates/README.md
> +Please feel to contribute or provide the feedback in discussions or via opening the issue in dotnet/templating repo.
removed other one

2023-01-16 12:57 UTC, JanKrivanek approved these changes
Overal looks good!

I have couple minor comments - but those are just ideas

2023-01-17 13:41 UTC, vlada-shubina commented on template_feed/Microsoft.TemplateEngine.Authoring.Templates/content/TemplatePackage/New.Template.Package.csproj
> +    <TargetFramework>net7.0</TargetFramework>
https://github.com/dotnet/templating/pull/5811 also is not yet merged.

2023-01-17 15:33 UTC, baronfel approved these changes

2023-01-17 17:41 UTC, vlada-shubina commented on template_feed/Microsoft.TemplateEngine.Authoring.Templates/content/TemplatePackage/New.Template.Package.csproj
> +    <TargetFramework>net7.0</TargetFramework>
okay, it was merged via other PR, then makes sense - will add later.

2023-01-18 09:08 UTC, vlada-shubina commented on template_feed/Microsoft.TemplateEngine.Authoring.Templates/content/TemplateJson/template.json
> +    "TODO: fill classification here. Common classifications are: Library, Test, Web etc. Each classification should be a separate element of the array."
Added, though classifications description in the doc is not great :(

2023-01-18 09:08 UTC, vlada-shubina commented on template_feed/Microsoft.TemplateEngine.Authoring.Templates/content/TemplatePackage/New.Template.Package.csproj
> +    <TargetFramework>net7.0</TargetFramework>
updated

2023-01-18 09:09 UTC, vlada-shubina commented on test/Microsoft.TemplateEngine.Authoring.Templates.IntegrationTests/AuthoringTemplatesTests.cs
> +            .WithInstantiationThroughTemplateCreatorApi(new Dictionary<string, string?>());
i'm fan of KISS in tests. 
Framework is changed once a year, and it's ok to update snapshots when it happens - there were only few adjustments needed.

2023-01-18 11:17 UTC, merged

2023-01-18 11:18 UTC, vlada-shubina commented
/backport to release/7.0.2xx