Add NuGet to dependency flow
dotnet/templating pull request #6360
Opened 2023-04-07 17:12 UTC by mthalman

### Problem

When attempting to enable [PVP flow](https://github.com/dotnet/source-build/issues/3043) for the templating repo, it was discovered that the repo has a dependency on the previously released version of NuGet (6.5.0) rather than the in-development version (6.6.0). This would require [SBRPs](https://github.com/dotnet/source-build-reference-packages) to be defined for those package versions. Instead, it seems more appropriate to update the repo to enable dependency flow for NuGet.

### Solution

I've enabled dependency flow for NuGet.Credentials (for the `VS 17.6` channel). Since the versions are consistent across the NuGet packages, I've reused that version for the other NuGet dependent packages that are also referenced.

Once merged, I'll create a darc subscription with the following settings:

```
https://github.com/nuget/nuget.client (VS 17.6) ==> 'https://github.com/dotnet/templating' ('main')
  - Update Frequency: EveryBuild
  - Enabled: True
  - Batchable: False
  - PR Failure Notification tags:
  - Merge Policies: Standard
```

2023-04-07 18:05 UTC, mmitche commented
@vlada-shubina What do you think?

IIRC, some of these versions actually make it into the templates themselves. That may mean that they might need to stay at an old, stable version rather than picking up the live version.

2023-04-11 18:19 UTC, vlada-shubina commented
> @vlada-shubina What do you think?
> 
> 
> 
> IIRC, some of these versions actually make it into the templates themselves. That may mean that they might need to stay at an old, stable version rather than picking up the live version.

We decided not to use the latest version for NuGet for two reasons:
- (main reason) latest NuGet packages are not available on NuGet.org which makes preview and in some cases release template engine NuGet packages pushed to NuGet.org unusable
- we had issues with having different versions in dotnet/sdk and dotnet/templating 


To accept this PR, we need to ensure that NuGet NuGet packages are always pushed to NuGet.org together with .NET packages which wasn't the case with .NET 7.

2023-04-11 18:20 UTC, vlada-shubina requested changes
To accept this PR, we need to ensure that preview NuGet.* packages are pushed to nuget.org

2023-04-13 19:15 UTC, mthalman commented
> To accept this PR, we need to ensure that preview NuGet.* packages are pushed to nuget.org

Based on this information, I'll abandon these changes and go ahead with adding these NuGet packages to SBRP: https://github.com/dotnet/source-build-reference-packages/pull/608.

2023-04-13 19:15 UTC, closed without merging