Remove .NET Standard 1.x dependencies and cleanup
dotnet/templating pull request #6403
Opened 2023-04-17 09:06 UTC by ViktorHofer

1. Avoid .NET Standard 1.x dependencies in the repository completely. The remaining test package dependency that brings netstandard1.x is FakeItEasy. For that one, upgrade the transitive Castle.Core dependency to 5.x. I also opened an issue in FakeItEasy to discuss upgrading the Castle.Core dependency. This results in the repository not being affected by CVEs / vulnerable packages like System.Private.Uri that are part of the .NET Standard 1.x dependency graph. (cc @MichaelSimons, @mmitche, @ericstj)
2. Upgrade projects that use "System.Runtime.Loader" from netstandard2.0 to .NETCoreApp as that API is only availble on .NETCoreApp anyway. The package that was used hasn't shipped for years anymore and was never intended to be used on .NET Standard (support for it was later removed). Because of that, new nullable reference type errors were raised by the compiler which I suppressed temporarily by downgrading the Nullable property to "annotations".
3. Clean-up code files
   - Use consistent indentation
   - Empty lines after Project and before closing tag
   - Empty lines between Property/Item groups
   - Remove unused msbuild properties
   - Delete unused or non-necessary files (i.e. Build.props).
   - Remove unnecessary "<?xml" and "ToolsVersion" tags in files that don't need them (msbuild).
   - Define Newtonsoft.Json package version in Packages.props instead of hardcoding it where it is used.
   - Use the implicitly (by the SDK) defined #if NETFRAMEWORK compiler preprocessor directive instead of a custom "NETFULL" one.
   - Remove one "#nullable enable" statement that wasn't necessary anymore as all projects that included the source file already enabled nullable.
4. Use floating TFM version that is defined in Arcade: "NetCurrent"
5. For the .NET Framework TFM msbuild property, use the same nomenclature as in other repos.
6. Do not define a floating TFM msbuild property for netstandard2.0 as that TFM will never change to a higher version.
7. Change how the live Microsoft.NETCore.App targeting/runtime pack is upgraded in this repository to allow previous TFMs to be targeted as well (for msbuild tasks).
8. Remove the "PackSpecific" msbuild property and its conditions as .NET Framework assets can be built and packaged on Unix machines these days with the dynamic reference on .NET Framework targeting packs.

### Problem

### Solution

### Checks:
- [ ] Added unit tests
- [ ] Added `#nullable enable` to all the modified files [?](https://github.com/dotnet/templating/wiki/Contributing#coding-style)

2023-04-17 15:21 UTC, mmitche commented
Spring cleaning in .NET! Lovely @ViktorHofer

2023-04-18 14:07 UTC, vlada-shubina requested changes
There are couple of change requests inline.

For future, we try to do all formatting changes in separate commit, so they can be ignored when reviewing.

2023-04-18 14:07 UTC, vlada-shubina commented on test/Directory.Build.targets
> -    <PackageReference Condition="'$(IsTestProject)' == 'true'" Include="Newtonsoft.Json" Version="13.0.1" />
We had to add other package references to ensure no issues in CG. Has something changed since then?

2023-04-18 14:07 UTC, vlada-shubina commented on test/Microsoft.TemplateEngine.TestTemplates/test_templates/PostActions/RestoreNuGet/TwoProjectsFiles/Custom/MyTestProject.Tests/MyTestProject.Tests.csproj
> -  <ItemGroup>
This package reference is expected by tests and should be kept.

2023-04-18 14:07 UTC, vlada-shubina commented on test/Microsoft.TemplateEngine.TestTemplates/test_templates/PostActions/RestoreNuGet/TwoProjectsPrimaryOutputs/Custom/MyTestProject.Tests/MyTestProject.Tests.csproj
> -    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
This package reference is expected by tests and should be kept.

2023-04-18 14:07 UTC, vlada-shubina commented on tools/legacy-tools/BaselineComparer/BaselineComparer/BaselineComparer.csproj
> +    <TargetFramework>$(NetCurrent)</TargetFramework>
legacy tools are not used, and those changes might be skipped.

2023-04-18 14:07 UTC, vlada-shubina commented on Directory.Build.props
> -        <NETFullTargetFramework>net472</NETFullTargetFramework>
imo removing those properties is not for good. 
They name intention correctly and I prefer to keep them, also for .NET Standard.

They may be changed as
```
        <NETTargetFramework>$(NetCurrent)</NETTargetFramework>
        <NETStandardTargetFramework>netstandard2.0</NETStandardTargetFramework>
        <NETFullTargetFramework>net472</NETFullTargetFramework>
```
to remove `Core` and make use of automatic .NET (core) updates.

2023-06-14 10:10 UTC, YuliiaKovalova commented
Hi @ViktorHofer,

Do you still plan to deliver these changes?

2023-06-14 10:45 UTC, ViktorHofer commented
> Do you still plan to deliver these changes?

Yes, I will get back to in the coming weeks. Changing to draft PR.

2024-06-03 17:19 UTC, Forgind commented
@ViktorHofer, is it still true that you're planning to get back to this, or should we close it for now?

2024-06-09 09:46 UTC, closed without merging